---

  target_dir: '/home/apps/app_admin/'
  request_dir: "{{target_dir}}/{{CA_name}}/csr"
  keytool_path: '/opt/Oracle/Middleware/java/bin'
  CA_name: 'GCCA'
  machine_cert_jks_name: 'identity.jks'

  alias_items:
    - web2
    - web1
    - osb
    - portal
    - appwm3
    - appwm2
    - appwm1
    - appadm
    - ldap
    - vm3
    - vm2
    - vm4
    - vm7
    - appms2
    - axm
    - appms1
    - dbit
    - db
    - vm42
    - vm41
    - oam
    - vm3i
    - vm52
    - vm51
    - portalms2
    - portalms1
    - app.external
    - vm4i
    - vm62
    - webrel
    - vm61
    - appit1
    - app
    - portalrel
    - vm81
    - vm83
    - vm82


