---
# tasks file for update_ansible — present

# You can update the path that ansible is targetting by appending -e "ansible_path = [insert path here]"
- name: Updating Ansible from Repo...
  hg: repo='{{ansible_scm}}' dest='{{ansible_path}}' purge=yes force=yes

