---

- name: define arguments
  ansible.builtin.set_fact:
    args: /SP- /VERYSILENT /ALLUSERS /TASKS="addcontextmenufiles,addcontextmenufolders,associatewithfiles,!runcode"

- name: install VSCODE
  ansible.windows.win_package:
    path: "{{artifact_staging}}{{VSCODE}}"
    arguments: "{{ args }}"
    wait_for_children: true
    state: present
  register: install_status
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  changed_when: install_status.rc is defined and install_status.rc in [0]
  vars:
    ansible_become_user: "{{system_name}}\\{{domainadmin_user}}"
    ansible_become_password: '{{domain_password}}'

- name: debug
  ansible.builtin.debug:
    msg: "{{install_status}}"
