---
# A graceful reboot verified by users.vcenter_admin_userguestools status
- name: Reboot VM through vmware tools API
  delegate_to: localhost
  block:
  - name: Shutdown Host
    vmware_guest_powerstate:
      ansible.builtin.hostname: "{{ vmware.vcenter_hostname }}"
      username: "{{ users.vcenter_admin_user }}"
      password: "{{ users.vcenter_admin_password }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: shutdown-guest
      state_change_timeout: 1200

  - name: Wait for confirmation of Power off
    community.vmware.vmware_guest_info:
      ansible.builtin.hostname: "{{ vmware.vcenter_hostname }}"
      username: "{{ users.vcenter_admin_user }}"
      password: "{{ users.vcenter_admin_password }}"
      datacenter: "{{ vmware.datacenter }}"
      validate_certs: no
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: facts
    delay: 15
    retries: 5
    until: facts.instance.hw_power_status == "poweredOff"

  - name: Power on
    vmware_guest_powerstate:
      ansible.builtin.hostname: "{{ vmware.vcenter_hostname }}"
      username: "{{ users.vcenter_admin_user }}"
      password: "{{ users.vcenter_admin_password }}"
      name: "{{ inventory_hostname }}"
      validate_certs: no
      state: powered-on
      state_change_timeout: 1200

  - name: Wait for confirmation of VmwareGuestTools Running
    community.vmware.vmware_guest_info:
      ansible.builtin.hostname: "{{ vmware.vcenter_hostname }}"
      username: "{{ users.vcenter_admin_user }}"
      password: "{{ users.vcenter_admin_password }}"
      datacenter: "{{ vmware.datacenter }}"
      validate_certs: no
      name: "{{ inventory_hostname }}"
    register: facts
    delay: 60
    retries: 5
    until: facts.instance.guest_tools_status == "guestToolsRunning"
