---
## This role needs to be ran as the primary DC to work properly. Either switch roles to dc1, or set hosts in the playbook to the primaryDC 

# Remove unsupported IFC OU
# - name: Ensure {{pre_ifc}} OU is absent #to delete if protected
#   microsoft.ad.ou:
#     name: '{{pre_ifc}}'
#     state: absent

###Check for C:\GPO_XXXX according to ADD doc number

- name: Set environment color for IFC if even
  ansible.builtin.set_fact:
    color: 'BLUE'
  when: "{{ ifc[-1::] }} % 2 == 0"

- name: Set environment color for IFC if odd
  ansible.builtin.set_fact: 
    color: 'GREEN'
  when: "{{ ifc[-1::] }} % 2 != 0"

# Verify OUs are present
- name: Verify {{ domain_ou | upper }}_{{ color }} OU exists
  microsoft.ad.ou:
    name: '{{ domain_ou | upper }}_{{ color }}'
    protect_from_deletion: false
    state: present 

- name: Verify {{ domain_ou | upper }}_{{ color }} Servers OU exists
  microsoft.ad.ou:
    name: Servers
    path: OU={{ domain_ou | upper }}_{{ color }},DC={{ domain_ou }},DC=local
    protect_from_deletion: false
    state: present

- name: Verify {{ domain_ou | upper }}_{{ color }} Workstations OU exists 
  microsoft.ad.ou:
    name: Workstations
    path: OU={{ domain_ou | upper }}_{{ color }},DC={{ domain_ou }},DC=local
    protect_from_deletion: false
    state: present

- name: Verify {{ domain_ou | upper }}_{{ color }} VDI OU exists
  microsoft.ad.ou:
    name: VDI
    path: OU={{ domain_ou | upper }}_{{ color }},DC={{ domain_ou }},DC=local
    protect_from_deletion: false
    state: present

- name: Verify {{ domain_ou | upper }}_{{ color }} RHEL OU exists
  microsoft.ad.ou:
    name: RHEL
    path: OU={{ domain_ou | upper }}_{{ color }},DC={{ domain_ou }},DC=local
    protect_from_deletion: false
    state: present

# Verify Domain Controllers OU is present
- name: Verify Domain Controllers OU exists
  microsoft.ad.ou:
    name: Domain Controllers
    protect_from_deletion: false
    state: present
