---
listener_name: DB_1210
tmp_directory: /var/shares/cots/SQL
decompressed_directory: /var/tmp/SQL/
tmp_dmp_directory: /u02/data_dmp
data_pump_dir: /u02/oradata/example/dpdump
error_file: /tmp/db_import_ERROR_OCCURRED
ORACLE_HOME: /opt/oracle/app/ora_rmt/product/12.1.0

