---
ansible_secret_file_name: passwords.txt
ansible_secret_target: /etc/ansible

ansible_package_name: "ansible-{{ ansible_package_version }}"
ansible_package_version: 2.7.10

ansible_present_packages:
  - "{{ ansible_package_name }}"

ansible_latest_packages:
  - python2-idna
  - python2-pyvmomi
  - ansible-lint
  - zip
  - unzip

ansible_latest_state: present

ansible_artifact_staging_path: /var/artifact_staging
ansible_artifact_staging_owner: ansible
ansible_artifact_staging_group: ansible

python_packages_source_dir: /mnt/windows/common/Installers/Python/libs