#WebLogic User Configuration File; 2
#Thu Feb 26 13:10:12 GMT 2015
weblogic.management.username={AES}pZ4u8c9ymsMHJ/awiJX7BH8nARFUfCvDXo1Re61BLeI\=
weblogic.management.password={AES}D4qDAP3mCsuPXXV+ldcbrYveMLYuVTVX6BEl2J3ppTU\=
