---
# tasks file for update_packages — present

# Playbook to update to latest for all packages
- name: ensure latest versions of packages are installed
  ansible.builtin.yum: name=* state=latest
  become: true
  tags:
    - skip_ansible_lint