---
# tasks file for change_rel_index_urls — present

# This task is to update the urls for the index.html files after a clone.
# This was previously done in the changeGapCieUrls.sh shell script

- name: Update urls in index.html files
  become: true
  become_user: app_admin
  ansible.builtin.replace:
    dest: "/u02/www/html/app_release/index.html"
    regexp:  "{{ source }}"
    ansible.builtin.replace:  "{{ system }}"
