---
# tasks file for install_vmrc
# - name: Uninstall VMRC
#   ansible.windows.win_package:
#     path: "{{VMRC_install_loc}}{{vmrcOLD}}"
#     arguments: /qn /norestart
#     state: absent
#   become: true
#   become_method: runas
#   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
#   vars:
#     ansible_become_user: "{{system_name}}\\{{domainadmin_user}}"
#     ansible_become_password: '{{domain_password}}'
#   ignore_errors: yes

- name: Install VMRC without using the credentials
  ansible.windows.win_package:
    path: "{{artifact_staging}}{{vmrc}}"
    arguments: /s /v "/qn EULAS_AGREED=1"
    state: present
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{system_name}}\\{{domainadmin_user}}"
    ansible_become_password: '{{domain_password}}'
