---
docker_install_list:
   - container-selinux-2.107-3.el7.noarch.rpm
   - containerd.io-1.2.10-3.2.el7.x86_64.rpm 
   - docker-ce-cli-19.03.3-3.el7.x86_64.rpm
   - docker-ce-19.03.3-3.el7.x86_64.rpm
yum_repo: http://repo.example.coach/gaps
   