- name: "Checking for running fecru sessions"
  # this causes 2 processes to be running. That's why the size check later is less than 3
  ansible.builtin.shell: ps -ef | grep fecru
  register: fecru_svcs
  changed_when: False

- name: "Starting fecru"
  become: true
  ansible.builtin.command: "/opt/atlassian/fecru-4.5.1/bin/start.sh"
  when: fecru_svcs.stdout_lines|length < 3

  # TODO: review changed_when for: /opt/atlassian/fecru-4.5.1/bin/start.sh
- name: "Checking for running fecru sessions"
  ansible.builtin.shell: ps -ef | grep fecru
  register: fecru_svcs
  changed_when: False

- name: "Verify Fecru is started"
  ansible.builtin.fail:
    msg: |
      Could not find any running fecru processes on host!
  when: fecru_svcs.stdout_lines|length < 3