---
# tasks file for install_win_features — present

  
 ## In order for this to work you need the following vars (in hosts.yml) for it to work:  win_features

  - name: Install Windows Features
    ansible.windows.win_feature: 
      name: "{{ parameters.win_features }}"
      state: present
