---
# tasks file for add_consul_to_dns — present

# Add the consul IPs to the resolv.conf file if they don't exist

- block:
    - name: Update resolve.conf to contain entries to all consul instances
      ansible.builtin.template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        ansible.builtin.group: root
        mode: 0644
  become: true
