---
# tasks file for generate_machine_certs — present

# Create cert workspace
  - name: create machine cert workspace

    become_user: app_admin
    ansible.builtin.file:
      path: "{{target_dir}}/{{CA_name}}/cert_staging/"
      state: directory

# Create key pairs
  - name: remove old jks

    become_user: app_admin
    ansible.builtin.file:
      path: "{{target_dir}}/{{CA_name}}/cert_staging/{{machine_cert_jks_name}}"
      state: absent

  - name: Create keypairs

    become_user: app_admin
    ansible.builtin.command: "{{keytool_path}}/keytool -genkeypair -alias {{item}}.local -dname \"CN={{item}}.example.coach, OU=STRATCOM, OU=PKI, OU=DoD, O=U.S. Government, C=US\" -sigalg SHA256withRSA -keystore {{target_dir}}/{{CA_name}}/cert_staging/{{machine_cert_jks_name}} -keyalg rsa -keysize 2048 -validity 365 -storepass {{cert_pass}} -keypass {{cert_pass}}"
    loop:
      "{{alias_items}}"

    # TODO: review changed_when for: {{keytool_path}}/keytool -genkeypair -alias {{item}}.local -
  - name: Create certificate signing request (CSR)

    become_user: app_admin
    ansible.builtin.command: "{{keytool_path}}/keytool -certreq -sigalg SHA256withRSA -alias {{item}}.local -file {{request_dir}}/{{item}}.req -keystore {{target_dir}}/{{CA_name}}/cert_staging/{{machine_cert_jks_name}} -storepass {{cert_pass}} -keypass {{cert_pass}}"
    loop:
      "{{alias_items}}"
    # TODO: review changed_when for: {{keytool_path}}/keytool -certreq -sigalg SHA256withRSA -ali
