
export_nm_script: export_nm_config.py
gc2_wlst_path: "{{mw_home}}/oracle_common/common/bin/wlst.sh"
gc2_config_path: /home/apps/app_admin/gc2

# Node Manager Key and Config files
nm_Config_file: nmConfig.secure
nm_Key_file: nmKey.secure

# Node Manager user and listen port
nodemanager_username: 'wl_admin_user'
nm_listen_port: 5558

# Domain Name and directory path for the home
domains_home: '/u01/domains'
domain_name: 'wl_domain'
domain_home: '{{domains_home}}/{{domain_name}}'

# SSL specific settings
nm_type: 'ssl'
config_key: 'nmConfig.secure'
nm_key: 'nmKey.secure'
store_credentials: true

# Operating System user that the Node Manager runs as
os_user: app_admin


