#Node manager properties
#Tue Sep 20 19:29:24 GMT 2016
DomainsFile=/u01/domains/wl_domain/nodemanager/nodemanager.domains
LogLimit=0
PropertiesVersion=12.1
AuthenticationEnabled=true
NodeManagerHome=/u01/domains/wl_domain/nodemanager
JavaHome=/opt/Oracle/java
LogLevel=INFO
DomainsFileEnabled=true
StartScriptName=startWebLogic.sh
ListenAddress={{ansible_hostname}}.example.coach
NativeVersionEnabled=true
ListenPort=5558
LogToStderr=true
SecureListener=true
LogCount=1
StopScriptEnabled=false
QuitEnabled=false
LogAppend=true
StateCheckInterval=500
CrashRecoveryEnabled=false
StartScriptEnabled=true
LogFile=/u01/domains/wl_domain/nodemanager/nodemanager.log
LogFormatter=weblogic.nodemanager.server.LogFormatter
ListenBacklog=50
KeyStores=CustomIdentityAndCustomTrust
CustomIdentityKeyStoreFileName=/opt/identity/identity.jks
CustomIdentityKeyStorePassPhrase={{cert_pass}}
CustomIdentityAlias={{ansible_hostname}}.local
CustomIdentityPrivateKeyPassPhrase={{cert_pass}}
