---
- name: File target with block content
  become: true
  ansible.builtin.blockinfile:
    path: "{{ yum_repos_directory }}/{{ yum_repo_file }}"
    block: |
      [{{ item.name }}]
      name={{ item.name }}
      baseurl={{ item.endpoint_prefix }}{{ yum_repo_server }}/{{ item.endpoint }}
      gpgcheck={{ item.gpg }}
      enabled={{ item.enabled }}
    marker_begin: "{{ item.name }} BEGIN"
    marker_end: "{{ item.name }} END"
    owner: root
    ansible.builtin.group: root
    mode: '0644'
    state: present
    create: yes
  loop: "{{ yum_repo_endpoints }}"