#Servers.properties defines connection information
#for services used by the ISPAN system.

application.server=localhost

weblogic.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

#BEA LDAP Domain
weblogic.DOMAIN_NAME=vcie_domain

#true or false flag for sending notifications
#this is used by notificationmanager to determine if emails should be sent when a user resets a password.
notification.enabled=true

#BEA ALSB/OSB Administration Console Information
#Used in the Configuration Dashboard
esb.server.URL=osb.example.coach
esb.server.PORT=7011
esb.server.USER=wl_admin_user
esb.server.PASSWORD=kRB9ySwPpHkTCSoGmZpVvQ==
esb.server.PROTOCOL=t3
esb.services.url=http://vmlb.example.coach:10003
#URL from which the ESB can be accessed externally. Used for GCCS-J Callback
esb.external.url=http://trans.{{system}}.example.coach:50019

#Enter timeout in seconds.
esb.delegate.read.timeout=300

#Portal Remote Session information
portal.ENDPOINT=http://vmlb.example.coach:80/ptapi/services/QueryInterfaceAPI
#the following portal.server value is for the proxy url
portal.server=trans.{{system}}.example.coach
portal.entry.url=https://trans.{{system}}.example.coach/portal/server.pt
portal.entry.url.releasable=https://transrel.{{system}}.example.coach/portal/server.pt
portal.ptportal.schema=CP_Example_PTPORTAL
portal.ptportal.schema.releasable=CP_Example_SIPRRELPTPORTAL

# The following settings are for requests intended to go around the portal.  These should be set to the 
# server that is first hit by a user's client/browser.  In a normal cluster, that would be the proxy server.
nongatewayed.proxy.server=https://trans.{{system}}.example.coach
nongatewayed.proxy.server.releasable=https://transrel.{{system}}.example.coach

#Login URLs
#  Normal CIE Login
cie.login=https://trans.{{system}}.example.coach/app_main/
#  SIPR Rel Login
cie.login.sipr.rel=https://transrel.{{system}}.example.coach/app_release

#GSAT URLs
#  Normal GSAT
gsat.url=https://trans.{{system}}.example.coach/gsat/GSAT.do
#  SIPR Rel GSAT
gsat.url.sipr.rel=https://transrel.{{system}}.example.coach/gsat/GSAT.do

#Logout URLs
#  Normal CIE Logout
cie.logout=https://trans.{{system}}.example.coach/oam/server/logout?end_url=/authentication/logoutPage.do
#  SIPR Rel Logout
cie.logout.sipr.rel=https://transrel.{{system}}.example.coach/oam/server/logout?end_url=/authentication/logoutPage.do

#Map Service
map.ims.server=lnbncc05
map.sde.server=lnbncc21
map.sde.instance=5151
map.sde.user=sde_app
map.sde.password=XRt18AMZM4wINhqAEiaKJw==

#Contingency Planning Plan Manager Role
conplan.project.role.admin=Contingency Plan Manager

#Contingency Planning Search Manager Role
conplan.search.role.admin=Contingency Plan Search Manager

# GSAT Eventing Configuration

# GSAT Eventing JMS 
gsat.subscription.event.cf=gsat.eventing.jms.connectionFactory
gsat.subscription.event.queue=gsat.eventing.jms.queue
gsat.subscription.connection.mode=tmse


# Callback Web Services
tmse.eventing.callback.endpoint=http://vmlb.example.coach:10000/TmseEventsCallbackService/services/BatchedEvents
strikecoi.eventing.callback.endpoint=

#Path to default image to show in place of restricted images.  Location is relatiev to the imageserver base.
restricted.image.path=app/img/restricted.gif

# Default image used for cover page and header of briefings.  Location is relative to the imageserver base.
default.briefings.slideHeaderImage=gnci/images/System_Default_Slide_Header_Logo.gif
default.briefings.coverImage=gnci/images/System_Default_Title_Slide_Logo.gif

# Default image used for order header.  Location is relative to the imageserver base.
default.order.logoImage=gnci/images/System_Default_Slide_Header_Logo.gif

#Used by the endpoint Dashboard from GSAT (non gatewayed environment)
nongatewayed.stylesheet.location=plumtree/common/public/css
nongatewayed.images.location=https://trans.{{system}}.example.coach/imageserver/
nongatewayed.images.location.releasable=https://transrel.{{system}}.example.coach/imageserver/
nongatewayed.staticassets.location=https://trans.{{system}}.example.coach/static-assets/
nongatewayed.staticassets.location.releasable=https://transrel.{{system}}.example.coach/static-assets/

# The following property should match the property above except that it needs to be non-ssl.  This setting
# should only be used by code running on the application server needing to reach the image server, and 
# therefore will not need to be encrypted.  Both properties need to end with the "/".
nongatewayed.images.location.internal=http://vmlb.example.coach:80/imageserver/

# Used to pull images into PDF briefs MUST BE NON-SSL!
nongatewayed.internal.url=http://vmlb.example.coach:10000/

#Used for configurations with separate itrace servers
nongatewayed.internal.itrace.url=http://appit1.example.coach:7101/

# Used for ICEWS LRP references
icews.internal.url=http://appit1.example.coach:7101/

# Used to locate ICEWS EHCache EJB
icews.service.url=t3://appit1.example.coach:7101

#URL for popup briefs. Will change for each environment. DO NOT end property with the "/".
popup.brief.url=https://trans.{{system}}.example.coach
popup.brief.url.releasable=https://transrel.{{system}}.example.coach

# URL for popup Assessment History Graphs.  Will change for each environment.
popup.assessmenthistorygraph.url=https://trans.{{system}}.example.coach/imageserver/AnyChart/AssessmentHistoryGraph.html
popup.assessmenthistorygraph.url.releasable=https://transrel.{{system}}.example.coach/imageserver/AnyChart/AssessmentHistoryGraph.html


#OIM Service Info
oim.service.delegate.username=xelsysadm
oim.service.delegate.password=3hPlhDkH3o++A1ahaUl1yA==
oim.service.url=t3://vm2.example.coach:14000
oim.service.init.ctx.factory=weblogic.jndi.WLInitialContextFactory

oam.certification.auth.url=https://trans.{{system}}.example.coach/authentication/CertificateAuthentication.do
oam.certification.auth.url.rel=https://transrel.{{system}}.example.coach/authentication/CertificateAuthentication.do

oim.auth.scheme.ldap=ISPANAuthenticationScheme
oim.auth.scheme.ldap.rel=ISPANAuthenticationSchemeRel
oim.auth.scheme.x509=ISPANX509Scheme


# OIM user properties.  These are different than LDAP properties.  OIM properties are case-sensitive (unlike LDAP).
oim.USER_GROUP_BASE=cn=Users,dc=cie,dc=local
oim.USER_DSN_TELEPHONENUMBER_ATTRIBUTE=dsnTelephoneNumber
oim.USER_DSN_FAX_NUMBER_ATTRIBUTE=cpDsnFaxNumber
oim.USER_EMAIL_ATTRIBUTE=Email
oim.USER_FAX_NUMBER_ATTRIBUTE=Fax
oim.USER_FNAME_ATTRIBUTE=First Name
oim.USER_LNAME_ATTRIBUTE=Last Name
oim.USER_NAME_ATTRIBUTE=Common Name
oim.USER_OFFICE_SYMBOL_ATTRIBUTE=officeSymbol
oim.USER_ORGANIZATION_ATTRIBUTE=cpOrganization
oim.USER_POSTAL_ADDRESS_ATTRIBUTE=postalAddress
oim.USER_RANK_ATTRIBUTE=cpservicerank
oim.USER_COUNTRY_ATTRIBUTE=cpcitizenshipcountry
oim.USER_BRANCH_ATTRIBUTE=cpserviceorganization
oim.USER_STATION_ATTRIBUTE=station
oim.USER_TELEPHONENUMBER_ATTRIBUTE=Telephone Number
oim.USER_CERT_DN=cpCertAssociationId
oim.USER_SECURITYCLASS_ATTRIBUTE=securityClass
oim.USER_SECURITYSCI_ATTRIBUTE=securitySci
oim.USER_SECURITYDISSEM_ATTRIBUTE=securityDissem
oim.USER_SECURITYRELTOGROUP_ATTRIBUTE=securityRelToGroup
oim.search.USER_ORGANIZATION_ATTRIBUTE=organization

oim.SYSTEM_ADMIN_REQUEST_EMAIL_GROUPS=ISPAN System Administrator

oim.USER_PASSWORD_EXPIRED_ATTRIBUTE=usr_pwd_expired
oim.USER_LOCKED_ATTRIBUTE=usr_locked

# OIM role (ldap group) properties.  These are different than LDAP properties.  OIM properties are case-sensitive (unlike LDAP).
oim.GROUP_BASE=Default
oim.GROUP_NAME_ATTRIBUTE=Role Name
oim.GROUP_TYPE_ATTRIBUTE=cpGroupType
oim.GROUP_DISPLAY_ORDER_ATTRIBUTE=cpDisplayOrder

# User names in our OAM system are found on the request header as OAM_REMOTE_USER.
oim.REQUEST_HEADER_USER_NAME_ATTRIBUTE=OAM_REMOTE_USER

#name translation can be one of NONE,TEMPLATE, or REVERSE.  The default is NONE.
oim.ldap.distinguished.name.translation=REVERSE

oim.ldap.SECURITY_AUTHENTICATION=simple

oim.ENFORCE_SINGLE_EMAIL_ADDRESS_PER_ACCOUNT=false

oim.ADMIN_SYSTEM_EMAIL_GROUPS=AuthenticatedGroup
oim.ADMIN_SYSTEM_EMAIL_GROUPS=SIPRRelGroup

#DO NOT REMOVE THIS LINE _ IT MUST ALWAYS BE THE LAST LINE IN THIS FILE=======
