---
# tasks file for sshd_config — present

#####################################################################
## Do sshd_config here instead of letting ipa_client_install do it ##
#####################################################################
- block:
    - name: Check if KerberosAuthentication is already defined
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/ssh/sshd_config"
        regexp: "^KerberosAuthentication"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check
    - name: Replace KerberosAuthentication if defined
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^KerberosAuthentication"
        line: "KerberosAuthentication no"
      when: check.found == 1
    - name: Add KerberosAuthentication if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/ssh/sshd_config"
        line: "KerberosAuthentication no"
        insertbefore: '^Match'
        firstmatch: true
      when: check.found == 0

    - name: Check if PubkeyAuthentication is already defined
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/ssh/sshd_config"
        regexp: "^PubkeyAuthentication"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check
    - name: Replace PubkeyAuthentication if defined
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
      when: check.found == 1
    - name: Add PubkeyAuthentication if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/ssh/sshd_config"
        line: "PubkeyAuthentication yes"
        insertbefore: '^Match'
        firstmatch: true
      when: check.found == 0

    - name: Check if UsePAM is already defined
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/ssh/sshd_config"
        regexp: "^UsePAM"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check
    - name: Replace UsePAM if defined
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^UsePAM"
        line: "UsePAM yes"
      when: check.found == 1
    - name: Add UsePAM if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/ssh/sshd_config"
        line: "UsePAM yes"
        insertbefore: '^Match'
        firstmatch: true
      when: check.found == 0

    - name: Check if GSSAPIAuthentication is already defined
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/ssh/sshd_config"
        regexp: "^GSSAPIAuthentication"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check
    - name: Replace GSSAPIAuthentication if defined
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^GSSAPIAuthentication"
        line: "GSSAPIAuthentication yes"
      when: check.found == 1
    - name: Add GSSAPIAuthentication if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/ssh/sshd_config"
        line: "GSSAPIAuthentication yes"
        insertbefore: '^Match'
        firstmatch: true
      when: check.found == 0

    - name: Check if AuthorizedKeysCommand is already defined
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/ssh/sshd_config"
        regexp: "^AuthorizedKeysCommand"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check
    - name: Replace AuthorizedKeysCommand if defined
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^AuthorizedKeysCommand"
        line: "AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys"
      when: check.found == 1
    - name: Add AuthorizedKeysCommand if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/ssh/sshd_config"
        line: "AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys"
        insertbefore: '^Match'
        firstmatch: true
      when: check.found == 0

    - name: restart ssshd service
      ansible.builtin.service:
        name: sshd
        state: restarted
  become: true
