#!/bin/bash
#
#----------------------------------------------------------------------------------------------------
# Purpose: 
# This is a temporary bridge capability - meant to emulate the legacy kumpsend binary (part of Tivoli Monitoring)
#  and route those calls through Nagios instead of Tivoli.
#----------------------------------------------------------------------------------------------------
# Background:
# The original kumpsend binary used the following interface spec:
#
##
## Syntax:
##   kumpsend cat=<C|W|I> [ack=<y|n>] msg="Message Text"
##
##     Usage:
##       kumpsend msg=Message dp=DP_HostName ip=TCPIP_Version port=DP_Listen_Port ack=y|n cat=Category
##      
##       Required parameter:
##                msg= Post message text, enclosed in double quotes, to send to DP
##       Optional parameters:
##                 dp= Target DP host name, default to local machine
##               port= Target DP listening port, default to 7575
##                 ip= TCPIP version, default to 4 for IPv4
##                ack= Yes or No that message requires DP acknowledgment, default No
##                cat= Post message category,
##                     standard defined categories are:
##                              I - Information (default)
##                              O - Operation
##                              P - Application
##                              S - System
##                              N - Network
##                              A - Alert
##                              C - Critical
##                              W - Warning
##                              R - Reset
##                              D - Detail
##       Return codes:
##                  0= Success
##                  1= Invalid local socket environment
##                  2= Input parameter error
##                  3= Failure to contact Target DP
##
#
# Change Log
#----------------------------------------------------------------------------------------------------
#    2017-07-18 - CBN          - v1.0  - Original creation - Linux
#    2018-06-21 - Tony Widhalm - v1.1  - Solaris version
#    2018-08-09 - CBN	       - v1.2  - Merged aix/linux/solaris versions and bugfix for non-printing chars
#    2018-08-22 - CBN	       - v1.3  - Bugfix for embedded \n characters
#    2020-09-16 - CBN          - v1.4  - remove hardcoded /usr/local/bin dependency for send_nrdp.sh
#

print_help() {
  grep "^##" $0 | cut -c3-
}

# Platform-specific settings
case `uname` in
    AIX)  
	LD_LIBRARY_PATH=/usr/lib:/opt/freeware/lib                                               
	export LD_LIBRARY_PATH
	;;
esac

# Assume NRDP is in the same directory as this script. If not, check /usr/local/bin or assume it is in the path
THIS_DIR=`cd $(dirname $0); pwd`
for NRDP in ${THIS_DIR}/send_nrdp.sh /usr/local/bin/send_nrdp.sh `which send_nrdp.sh 2>/dev/null`
do 
   if [[ -f "$NRDP" ]];then break; fi 
done

NAGIOS_SERVICE="Legacy Kumpsend Notifications"

# Process arguments
# This getopt routine helps handle spaces and quoted arguments, etc.
TEMP=`getopt -o h --long msg:cat:ack: -n 'kumpsend' -- "$@"`

ACK="no"
while true; do
   case "$1" in
	msg=*) MESSAGE=`echo "$1"|cut -d= -f2|sed 's/|/\//g'|sed 's/[^[:print:]]//'|sed 's/\\\n/ /g'|tr '\n' ' '`; shift
		# The message replaces all pipe characters with a forward slash and strips non-printing and carriage returns.
		# The pipe means something special to Nagios
		;;
	cat=*) CATEGORY=`echo "$1"|cut -d= -f2`; shift;;
	ack=*) ACK=`echo "$1"|cut -d= -f2`; shift;;
        -h|--help) print_help; exit 0;;
	--) shift; break;;
	*) 
	   # Handle extraneous arguments
	   #  we purposefully ignore dp (tivoli server)
	   if [[ -z "$1" ]]; then break; else shift; fi
	   ;;
   esac
done

CATEGORY="`echo ${CATEGORY} | tr -s '[:lower:]' '[:upper:]'`" 

# Verify we were given required information..
 
if [[ -z "$MESSAGE" ]]; then echo "Message not provided"; exit 1; fi
if [[ -z "$CATEGORY" ]]; then CATEGORY="I"; fi

# Map Tivoli categories to nagios values
case "${CATEGORY}" in
   I|O|P|S|N|D|R) NAGCAT=0;;
   W|A) NAGCAT=1;;
   C) NAGCAT=2;;
   *) echo "Unknown category specified!"; exit 1;; 
esac

# Send the message to Nagios
if [[ -f $NRDP ]]; then
   OUT=`$NRDP -s "$NAGIOS_SERVICE" -S $NAGCAT -o "$MESSAGE"`
   if [[ $? -gt 0 ]]; then echo "Error generating Nagios message. $OUT"; exit 2; fi 
   #display generic tivoli acknowledgment
   if [[ `echo "$ACK"|grep -i "y"` ]]; then echo -e "Acknowledgment stamp 123456789\nSend post message to Nagios host successful. $OUT"; fi
else
   echo "Error: Nagios client send_nrdp.sh not found!"
   exit 2
fi
